# Generated by Django 5.0.3 on 2024-03-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20240317_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiver_account',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Transfer', 'Transfer'), ('Payment', 'Payment'), ('Gift', 'Gift'), ('Other', 'Other')], max_length=20),
        ),
    ]
