# Generated by Django 5.0.3 on 2024-03-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_bankaccount_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_holder',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_number',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
