# Generated by Django 5.0.3 on 2024-03-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_remove_bankaccount_account_holder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='user',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='bank Name'),
        ),
    ]
