# Generated by Django 5.0.3 on 2024-03-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_remove_bankaccount_user_bankaccount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Transfer', 'Transfer'), ('Payment', 'Payment'), ('Withdraw', 'Withdraw'), ('Gift', 'Gift'), ('Other', 'Other')], max_length=20),
        ),
    ]
