# Generated by Django 5.0.3 on 2024-04-23 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_transaction_receiver_account_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-id']},
        ),
    ]
